<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.10">
  <POU Name="POU" Id="{f05d997b-04f7-443c-bc9a-8b59643a234f}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION POU : BOOL
VAR_INPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="POU">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>