<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.10">
  <POU Name="MAIN" Id="{ac89f347-c6c6-419e-a490-7d92bdd5a582}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[IF Inputs.bEnableSimulation THEN
	CraneSimulation();
END_IF;
]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="10" Count="0" />
      <LineId Id="2" Count="0" />
      <LineId Id="11" Count="1" />
    </LineIds>
  </POU>
</TcPlcObject>