<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.10">
  <POU Name="F_RadToDeg" Id="{f37597c2-ea64-4fce-8450-e12d5fb83a5c}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_RadToDeg : LREAL
VAR_INPUT
	fRad :LREAL;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_RadToDeg := fRad * (180/PI);]]></ST>
    </Implementation>
    <LineIds Name="F_RadToDeg">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>